# docker-compose file for starting sql-server container.
version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
